# Generated by cucumber-sinatra. (2015-01-12 20:34:06 +0000)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'lib/to_do.rb')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'

Capybara.app = Todo

class TodoWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  TodoWorld.new
end
